services:
  backend:
    container_name: backend
    env_file:
      - .env
    build: ./backend/
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /opt/app/backend/
        - action: rebuild
          path: ./backend/package.json
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    container_name: frontend
    environment:
      - PORT=3001
    build: ./frontend/
    ports:
      - 3001:3001
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /opt/app/frontend/
        - action: rebuild
          path: ./frontend/package.json
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379:6379
    volumes:
      - redis-data:/data/
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    expose:
      - 27017:27017
    volumes:
      - mongo-data:/data/db/

volumes:
  redis-data:
    driver: local
  mongo-data:
    driver: local

